amqp_url = "amqps://message-bus:5671/%2F"
publish_exchange = "amq.topic"
callback = "robosignatory.consumer:Consumer"

[[bindings]]
queue = "robosignatory"
exchange = "amq.topic"
routing_keys = [
    "local-koji.robosignatory.xml-sign",
    "local-koji.buildsys.tag",
]

[tls]
ca_cert = "/etc/pki/koji/koji_ca_cert.crt"
keyfile = "/etc/pki/koji/robosignatory.key"
certfile = "/etc/pki/koji/robosignatory.crt"

[client_properties]
app = "RoboSignatory"

[queues.robosignatory]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[qos]
prefetch_size = 0
prefetch_count = 15

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.robosignatory]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "INFO"
handlers = ["console"]

[consumer_config]

    [consumer_config.signing]
    backend = "sigul"
    user = "robosignatory"
    passphrase_file = "/etc/pki/koji/robosignatory.pass"
    config_file = "/etc/sigul/client.conf"

    [consumer_config.koji_instances]
        [consumer_config.koji_instances.primary]
        url = "https://koji-hub/kojihub"

            [consumer_config.koji_instances.primary.options]
            authmethod = "ssl"
            cert = "/etc/pki/koji/robosignatory.pem"
            serverca = "/etc/pki/koji/koji_ca_cert.crt"

            [[consumer_config.koji_instances.primary.tags]]
            from = "f36-addons-signing-pending"
            to = "f36-addons"
            key = "fedora-addons"
            keyid = "REPLACE-ME"

    # These keys need to be set even though they're never used
    [consumer_config.ostree_refs]
    [consumer_config.coreos]
    bucket = "INVALID"

        [consumer_config.coreos.aws]
        region = "INVALID"
        access_key = "INVALID"
        access_secret = "INVALID"
