---
services:
  # Koji < 1.30 does not work with Postgres 14
  db:
    image: docker.io/library/postgres:13.8
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
      POSTGRES_USER: koji
      POSTGRES_DB: koji
    secrets:
      - koji-postgres-password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "koji"]
      interval: 5s
      timeout: 5s
      retries: 10

  koji-hub:
    build:
      context: ./koji-hub
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-postgres-password
      - koji-hub-certificate-key
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
      KOJI_HUB_CERTIFICATE_KEY: /run/secrets/koji-hub-certificate-key
    volumes:
      - kojidata:/mnt/koji
    networks:
      - db
      - koji-backend
    expose:
      - "443"
    ports:
      - "8080:443"
    healthcheck:
      test: ["CMD", "koji", "-p", "localhost", "moshimoshi"]
      interval: 5s
      timeout: 5s
      retries: 10

  koji-sweep-db:
    build:
      context: ./koji-sweep-db
    # the sweep job only needs the database to be up and not the koji-hub,
    # but set koji-hub as the dependency to ensure that the database has been initialized
    depends_on:
      koji-hub:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-postgres-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
    networks:
      - db

  koji-admin:
    build:
      context: ./koji-admin
    depends_on:
      koji-hub:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-admin-certificate-key
    environment:
      KOJI_ADMIN_CERTIFICATE_KEY: /run/secrets/koji-admin-certificate-key
      KOJI_ADMIN_ADD_USERS: "koji-user"
    networks:
      - koji-backend

volumes:
  db:
    driver: local
  kojidata:
    driver: local

networks:
  db:
    internal: true
  koji-backend:
    internal: true

secrets:
  koji-postgres-password:
    external: true
  koji-hub-certificate-key:
    external: true
  koji-admin-certificate-key:
    external: true
