---
services:
  # Koji < 1.30 does not work with Postgres 14
  db:
    image: docker.io/library/postgres:13.8
    command: postgres -c 'max_connections=200'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
      POSTGRES_USER: koji
      POSTGRES_DB: koji
    secrets:
      - koji-postgres-password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "koji"]
      interval: 5s
      timeout: 5s
      retries: 10

  koji-hub:
    build:
      context: ./koji-hub
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-postgres-password
      - koji-hub-certificate-key
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
      KOJI_HUB_CERTIFICATE_KEY: /run/secrets/koji-hub-certificate-key
    volumes:
      - kojidata:/mnt/koji
    networks:
      - db
      - koji-backend
    expose:
      - "443"
    ports:
      - "8081:443"
    healthcheck:
      test: ["CMD", "koji", "-p", "localhost", "moshimoshi"]
      interval: 5s
      timeout: 5s
      retries: 10

  koji-sweep-db:
    build:
      context: ./koji-sweep-db
    # the sweep job only needs the database to be up and not the koji-hub,
    # but set koji-hub as the dependency to ensure that the database has been initialized
    depends_on:
      koji-hub:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-postgres-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/koji-postgres-password
    networks:
      - db

  koji-admin:
    build:
      context: ./koji-admin
    depends_on:
      koji-hub:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-admin-certificate-key
    environment:
      KOJI_ADMIN_CERTIFICATE_KEY: /run/secrets/koji-admin-certificate-key
      KOJI_ADMIN_ADD_USERS: "koji-user koji-builder-probe"
      KOJI_ADMIN_BUILDERS: "x86_64 aarch64"
      KOJI_ADMIN_BUILDER_aarch64: "aarch64"
      KOJI_ADMIN_BUILDER_x86_64: "x86_64"
    networks:
      - koji-backend

  koji-web:
    build:
      context: ./koji-web
    depends_on:
      koji-hub:
        condition: service_healthy
    restart: unless-stopped
    secrets:
      - koji-web-secret
      - koji-web-certificate-key
    environment:
      KOJI_WEB_SECRET_FILE: /run/secrets/koji-web-secret
      KOJI_WEB_CERTIFICATE_KEY: /run/secrets/koji-web-certificate-key
    networks:
      - koji-backend
    ports:
      - "8080:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/etc/pki/koji/koji_ca_cert.crt", "https://localhost/koji"]
      interval: 5s
      timeout: 5s
      retries: 10

  git:
    build:
      context: ./git
    restart: unless-stopped
    networks:
      - git
    volumes:
      - type: bind
        source: ${KOJI_GIT_PATH:-/var/lib/git/local-koji}
        target: /var/lib/git
        read_only: true

  koji-builder-aarch64:
    build:
      context: ./koji-builder
      args:
        arch: aarch64
        dockerarch: linux/arm64
    restart: unless-stopped
    networks:
      - git
      - dist-git
      - koji-backend
    volumes:
      - kojidata:/mnt/koji:ro
    depends_on:
      koji-admin:
        condition: service_started
      git:
        condition: service_started
    secrets:
      - koji-builder-aarch64-certificate-key
      - koji-builder-probe-certificate-key
    environment:
      KOJI_BUILDER_CERTIFICATE_KEY: /run/secrets/koji-builder-aarch64-certificate-key
      KOJI_BUILDER_PROBE_CERTIFICATE_KEY: /run/secrets/koji-builder-probe-certificate-key
    cap_add:
      - SYS_ADMIN

  koji-builder-x86_64:
    build:
      context: ./koji-builder
      args:
        arch: x86_64
        dockerarch: linux/amd64
    restart: unless-stopped
    networks:
      - git
      - dist-git
      - koji-backend
    volumes:
      - kojidata:/mnt/koji:ro
    depends_on:
      koji-admin:
        condition: service_started
      git:
        condition: service_started
    secrets:
      - koji-builder-x86_64-certificate-key
      - koji-builder-probe-certificate-key
    environment:
      KOJI_BUILDER_CERTIFICATE_KEY: /run/secrets/koji-builder-x86_64-certificate-key
      KOJI_BUILDER_PROBE_CERTIFICATE_KEY: /run/secrets/koji-builder-probe-certificate-key
    cap_add:
      - SYS_ADMIN

  kojira:
    build:
      context: ./kojira
    restart: unless-stopped
    networks:
      - koji-backend
    volumes:
      - kojidata:/mnt/koji
    depends_on:
      koji-admin:
        condition: service_started
      koji-hub:
        condition: service_healthy
    secrets:
      - kojira-certificate-key
    environment:
      KOJIRA_CERTIFICATE_KEY: /run/secrets/kojira-certificate-key

  dist-git:
    build:
      context: ./dist-git
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${KOJI_GIT_PATH:-/srv/koji-git}
        target: /var/lib/dist-git/git
        read_only: true
      - lookaside_cache:/var/lib/dist-git/cache/lookaside/pkgs
    networks:
      - dist-git
    secrets:
      - dist-git-certificate-key
    environment:
      DIST_GIT_CERTIFICATE_KEY: /run/secrets/dist-git-certificate-key
    ports:
      - "8082:443"

volumes:
  db:
    driver: local
  kojidata:
    driver: local
  lookaside_cache:
    driver: local

networks:
  db: {}
  koji-backend: {}
  git: {}
  dist-git: {}

secrets:
  koji-postgres-password:
    external: true
  koji-hub-certificate-key:
    external: true
  koji-admin-certificate-key:
    external: true
  koji-web-certificate-key:
    external: true
  koji-web-secret:
    external: true
  koji-builder-probe-certificate-key:
    external: true
  koji-builder-aarch64-certificate-key:
    external: true
  koji-builder-x86_64-certificate-key:
    external: true
  kojira-certificate-key:
    external: true
  dist-git-certificate-key:
    external: true
