amqp_url = "amqps://message-bus:5671/%2F"
publish_exchange = "amq.topic"
topic_prefix = "local-koji."

[tls]
ca_cert = "/etc/pki/koji/koji_ca_cert.crt"
keyfile = "/etc/pki/koji/koji-hub.key"
certfile = "/etc/pki/koji/koji-hub.crt"

[client_properties]
app = "Koji"

[qos]
prefetch_size = 0
prefetch_count = 15

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false
arguments = {}

[[bindings]]
queue = "robosignatory"
exchange = "amq.topic"
routing_keys = ["local-koji.buildsys.*"]

[queues.robosignatory]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.robosignatory]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "INFO"
handlers = ["console"]
